version: 0.2

env:
  variables:
    S3_BUCKET: "cargo-edi-frontend"
    CF_DIST_ID: "E3O3XAAZQTH5DM"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - node -v
      - npm -v
      - npm ci

  pre_build:
    commands:
      - echo "Skipping tests for now..."

  build:
    commands:
      - echo "Build Next.js and export static site..."
      - npm run build
      - npx next export -o out
      - test -d out || (echo "No 'out' directory!" && exit 1)
      - ls -la out

  post_build:
    commands:
      - echo "Sync to S3 - ${S3_BUCKET}"
      - aws s3 sync ./out s3://${S3_BUCKET} --delete --cache-control "public,max-age=31536000,immutable" --exclude "*.html"
      - aws s3 sync ./out s3://${S3_BUCKET} --delete --cache-control "public,max-age=0,must-revalidate" --include "*.html" --exclude "*"
      - echo "Invalidate CloudFront - ${CF_DIST_ID}"
      - aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: out

cache:
  paths:
    - node_modules/**/*
