version: 0.2

env:
  variables:
    S3_BUCKET: "cargo-edi-frontend"
    CF_DIST_ID: "E3O3XAAZQTH5DM" 

phases:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Running tests with coverage..."
      - npm test -- --coverage --watchAll=false

  build:
    commands:
      - echo "Building Next.js static site..."
      - npm run build
      - npx next export -o out
      - test -d out || (echo "No 'out' directory generated!" && exit 1)
      - ls -la out

  post_build:
    commands:
      - echo "Deploying to S3: $S3_BUCKET"
      - aws s3 sync ./out s3://$S3_BUCKET --delete --cache-control "public,max-age=31536000,immutable" --exclude "*.html"
      - aws s3 sync ./out s3://$S3_BUCKET --delete --cache-control "public,max-age=0,must-revalidate" --include "*.html" --exclude "*"
      - echo "Invalidating CloudFront: $CF_DIST_ID"
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
      - echo "Deployment done."

artifacts:
  files:
    - '**/*'
  base-directory: out
  name: build-output

cache:
  paths:
    - 'node_modules/**/*'
